// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovcomcjvhzgjxomzlocg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92Y29tY2p2aHpnanhvbXpsb2NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NDA1ODUsImV4cCI6MjA1NzIxNjU4NX0.UhKMFc2B3pMmB0QUkPEIhckbxIw26J8HwpcBQw80XQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);